version: '3.1'

services:
  # Servicio de Docker que corre una imágen de postgresql
  # Crea una base de datos "fruverdb" y al usuario "admin" con contraseña "Admin123"
  # Expone el puerto 5432 del contedor hacia el puerto 5432 del host
  # db:
  #   container_name: postgres
  #   image: postgres:14.2
  #   environment:
  #     - POSTGRES_DB=fruverdb
  #     - POSTGRES_USER=admin
  #     - POSTGRES_PASSWORD=Admin123
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./db/pgdata:/var/lib/postgresql/data
  #     - ./db/init.sql:/docker-entrypoint-initdb.d/data.sql
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=fruverdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=Admin123
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/scripts:/docker-entrypoint-initdb.d
