version: '3.1'

services:
  # Servicio de Docker que corre una imágen de MySQL
  # Crea una base de datos "fruverdb" y al usuario "admin" con contraseña "Admin123"
  # Expone el puerto 3306 del contedor hacia el puerto 3306 del host
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=fruverdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=Admin123
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/scripts:/docker-entrypoint-initdb.d
